/**
 * Precache service worker generator (S62).
 *
 * The static bundle ships ~110 separate unminified ES modules (~1.9 MB) and
 * re-downloads all of them on every cold load — the single biggest mobile-boot
 * cost. This generator emits a dependency-free sw.js per mount: versioned
 * precache (content-hash over every asset), cache-first with background
 * revalidate for same-origin static GETs, network-only for /api/ and the
 * freshness evidence surfaces, atomic cache swap on version change.
 *
 * Static-host-safe by construction: no dependencies, no external requests,
 * mount-relative scope (CSP already budgets worker-src 'self').
 */

import fs from "node:fs/promises";
import path from "node:path";
import { createHash } from "node:crypto";

// Never precached: freshness/evidence surfaces must always hit the network,
// and the worker must not cache itself or its manifest.
export const PRECACHE_EXCLUDES = Object.freeze([
  "sw.js",
  "precache-manifest.json",
  "_headers",
  "_health",
  "deploy-manifest.json",
  "edge-policy-receipt.json",
  "security.txt",
  ".well-known/security.txt",
  "404.html"
]);

const PRECACHE_EXTENSIONS = new Set([".html", ".js", ".css", ".json", ".svg", ".png", ".ico", ".webmanifest", ".txt"]);

export function shouldPrecache(relativePath) {
  const normalized = relativePath.replace(/\\/g, "/");
  if (PRECACHE_EXCLUDES.includes(normalized)) return false;
  if (normalized === "robots.txt" || normalized === "sitemap.xml") return false;
  // Built HTML references content-hashed copies. The plain assets remain for
  // back-compat direct hits, so precaching them would duplicate bytes and can
  // preserve stale Community Pulse language under its former URL.
  if (["styles.css", "community-stats.js"].includes(normalized)) return false;
  return PRECACHE_EXTENSIONS.has(path.extname(normalized).toLowerCase());
}

async function walkFiles(rootDir, current = rootDir, results = []) {
  const entries = await fs.readdir(current, { withFileTypes: true });
  for (const entry of entries) {
    const absolute = path.join(current, entry.name);
    if (entry.isDirectory()) {
      await walkFiles(rootDir, absolute, results);
    } else if (entry.isFile()) {
      results.push(path.relative(rootDir, absolute).replace(/\\/g, "/"));
    }
  }
  return results;
}

/**
 * Collect the precache manifest for one mount root. Returns entries with
 * per-file byte sizes plus a deterministic version hash over all contents.
 */
export async function buildPrecacheManifest(rootDir) {
  const files = (await walkFiles(rootDir)).filter(shouldPrecache).sort();
  const hash = createHash("sha256");
  let totalBytes = 0;
  const assets = [];
  for (const file of files) {
    const content = await fs.readFile(path.join(rootDir, file));
    hash.update(file);
    hash.update(content);
    totalBytes += content.length;
    assets.push({ url: `./${file}`, bytes: content.length });
  }
  return {
    version: hash.digest("hex").slice(0, 12),
    assetCount: assets.length,
    totalBytes,
    assets
  };
}

export function renderServiceWorker({ version, assets }) {
  const urls = assets.map((asset) => asset.url);
  return `/* Generated by scripts/lib/service-worker.mjs — do not edit by hand.
 * Precache version ${version} · ${urls.length} assets.
 * Cache-first with background revalidate for same-origin static GETs;
 * network-only for /api/ and freshness evidence surfaces. */
const CACHE_NAME = "vsfgm-precache-${version}";
const PRECACHE_URLS = ${JSON.stringify(urls)};
const NETWORK_ONLY = [/\\/api\\//, /_health$/, /deploy-manifest\\.json$/, /edge-policy-receipt\\.json$/];

self.addEventListener("install", (event) => {
  // Resilient install (S70): cache.addAll is atomic, so one 404 among all
  // precache URLs used to silently disable offline support entirely. Each URL
  // now caches independently; failures are counted and logged, and everything
  // that succeeded still serves from cache.
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) =>
        Promise.allSettled(PRECACHE_URLS.map((url) => cache.add(url))).then((results) => {
          const failed = results
            .map((result, index) => (result.status === "rejected" ? PRECACHE_URLS[index] : null))
            .filter(Boolean);
          if (failed.length) {
            console.warn("[sw] precache incomplete: " + failed.length + "/" + PRECACHE_URLS.length + " failed", failed.slice(0, 10));
          }
        })
      )
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((names) => Promise.all(
        names.filter((name) => name.startsWith("vsfgm-precache-") && name !== CACHE_NAME)
          .map((name) => caches.delete(name))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (NETWORK_ONLY.some((pattern) => pattern.test(url.pathname))) return;
  event.respondWith(
    caches.match(request, { ignoreSearch: false }).then((cached) => {
      const revalidate = fetch(request)
        .then((response) => {
          if (response && response.ok) {
            const copy = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => cached);
      return cached || revalidate;
    })
  );
});
`;
}

/**
 * Emit sw.js + precache-manifest.json into a built mount root.
 */
export async function emitServiceWorker(rootDir) {
  const manifest = await buildPrecacheManifest(rootDir);
  await fs.writeFile(path.join(rootDir, "sw.js"), renderServiceWorker(manifest), "utf8");
  await fs.writeFile(
    path.join(rootDir, "precache-manifest.json"),
    `${JSON.stringify(manifest, null, 2)}\n`,
    "utf8"
  );
  return manifest;
}

/**
 * Registration snippet injected into built HTML shells (never dev public/).
 * Dispatches vsfgm:sw-updated so the app can offer a reload toast.
 */
export const SW_REGISTRATION_SNIPPET = `<script>
if ("serviceWorker" in navigator) {
  window.addEventListener("load", () => {
    navigator.serviceWorker.register("./sw.js").then((registration) => {
      registration.addEventListener("updatefound", () => {
        const worker = registration.installing;
        if (!worker) return;
        worker.addEventListener("statechange", () => {
          if (worker.state === "activated" && navigator.serviceWorker.controller) {
            document.dispatchEvent(new CustomEvent("vsfgm:sw-updated"));
          }
        });
      });
    }).catch(() => {});
  });
}
</script>`;
